export const adminConstants = {
    REQUEST_USERINFO: 'REQUEST_USERINFO',
    RECEIVE_USERINFO: 'RECEIVE_USERINFO',
    REQUEST_TRANSINFO: 'REQUEST_TRANSINFO',
    RECEIVE_TRANSINFO: 'RECEIVE_TRANSINFO',
    REQUEST_ADDRESSES: 'REQUEST_ADDRESSES',
    RECEIVE_ADDRESSES: 'RECEIVE_ADDRESSES'
}
